CREATE TABLE ANAGRAFICA (
    IDanagrafica INT IDENTITY PRIMARY KEY,
    Cognome NVARCHAR(100) NOT NULL,
    Nome NVARCHAR(100) NOT NULL,
    Indirizzo NVARCHAR(100) NOT NULL,
    Città NVARCHAR(100) NOT NULL,
    CAP NVARCHAR(10) NOT NULL,
    Cod_Fisc NVARCHAR(16) NOT NULL
);